### ISSUE TITLE
error messages using Nimbus search with POV

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.nimbus#143]
Been testing POV as new daily driver due to Peter's "retirement" and the debrid kerfluffles, and when Nimbus search is set to use POV for searches it throws error messages on screen and in logs (see below). I at first thought it might be due to my build on Linux which has had multiple added/removed addons , so I did a clean install on android with my new RK3588 box (buzz p6) and it did the same thing. 

Then I went back and wiped the Linux build and the log segment below is from a brand new K21.1 with literally nothing but Nimbus and POV, and nothing configured or changed in either addon or skin except the Nimbus search preference was set to POV in Nimbus.

This was of particular note in the log since this was a clean install and Fen has never been on here and search was set to POV:
_2024-12-01 10:48:21.556 T:47      error <general>: Unable to find plugin plugin.video.fen
2024-12-01 10:48:21.556 T:47      error <general>: GetDirectory - Error getting plugin://plugin.video.fen/?_

BTW, I'd be happy to test anything for you so please let me know if there's anything I can do or if you need anything else from me.
Thank you!

kodi log from new clean 21.1 on Linux:
=========================
2024-12-01 10:48:21.529 T:7        info <general>: Loading skin file: Custom_1121_SearchResults.xml, load type: KEEP_IN_MEMORY
2024-12-01 10:48:21.534 T:7     warning <general>: Skin has invalid include: 
2024-12-01 10:48:21.534 T:7     warning <general>: Skin has invalid include: SearchHistory
2024-12-01 10:48:21.535 T:7     warning <general>: Skin has invalid include: MediaFlags
2024-12-01 10:48:21.538 T:7     warning <general>: Trying to add unsupported control type 7
2024-12-01 10:48:21.550 T:7        info <general>: Skipped 12 duplicate messages..
2024-12-01 10:48:21.550 T:7       error <general>: Window Translator: Can't find window dialogbusy
2024-12-01 10:48:21.556 T:47      error <general>: Unable to find plugin plugin.video.fen
2024-12-01 10:48:21.556 T:47      error <general>: GetDirectory - Error getting plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search_sets&query=
2024-12-01 10:48:21.567 T:7        info <general>: Unloaded skin
2024-12-01 10:48:21.568 T:7        info <general>:   load skin from: /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/ (version: 0.1.30)
2024-12-01 10:48:21.569 T:7        info <general>:   load fonts for skin...
2024-12-01 10:48:21.570 T:7        info <general>: Loading skin includes from /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml/Includes.xml
2024-12-01 10:48:21.579 T:7        info <general>: Error loading include file /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml/script-nimbus-search_history.xml: Failed to open file (row: 0, col: 0)
2024-12-01 10:48:21.583 T:7       error <general>: Error loading include file /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml/Custom_1121_SearchResults.xml: Root element <includes> required.
2024-12-01 10:48:21.588 T:7        info <general>: LoadFontsFromFile: Loading <fontset> with name 'Default' from '/home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml/Font.xml'
2024-12-01 10:48:21.592 T:7        info <general>: LoadTimers: Trying to load skin timers from /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml/Timers.xml
2024-12-01 10:48:21.592 T:7       error <general>: Misplaced [
2024-12-01 10:48:21.592 T:7       error <general>: Error parsing boolean expression control.hasfocus($param[list_id])
2024-12-01 10:48:21.592 T:7        info <general>:   load new skin...
2024-12-01 10:48:21.592 T:7        info <general>: Loading custom window XMLs from skin path /home/user01/.var/app/tv.kodi.Kodi/data/addons/skin.nimbus/xml
2024-12-01 10:48:21.593 T:7        info <general>:   initialize new skin...
2024-12-01 10:48:21.593 T:7        info <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.593 T:7        info <general>: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.594 T:7        info <general>: Loading skin file: DialogSeekBar.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.595 T:7        info <general>: Loading skin file: DialogExtendedProgressBar.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.595 T:7        info <general>: Loading skin file: Pointer.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.596 T:7        info <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.596 T:7        info <general>: Loading skin file: DialogVolumeBar.xml, load type: LOAD_ON_GUI_INIT
2024-12-01 10:48:21.596 T:7        info <general>:   skin loaded...
2024-12-01 10:48:21.596 T:7        info <general>: Loading skin file: Custom_1121_SearchResults.xml, load type: KEEP_IN_MEMORY
2024-12-01 10:48:21.598 T:7     warning <general>: Skin has invalid include: 
2024-12-01 10:48:21.598 T:7     warning <general>: Skin has invalid include: SearchHistory
2024-12-01 10:48:21.599 T:7     warning <general>: Skin has invalid include: MediaFlags
2024-12-01 10:48:21.601 T:7     warning <general>: Trying to add unsupported control type 7
2024-12-01 10:48:21.607 T:7        info <general>: Skipped 12 duplicate messages..
2024-12-01 10:48:21.607 T:7       error <general>: Window Translator: Can't find window dialogbusy
2024-12-01 10:48:21.629 T:7        info <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2024-12-01 10:48:22.455 T:66      error <general>: Unable to find plugin plugin.video.fen
2024-12-01 10:48:22.456 T:66      error <general>: GetDirectory - Error getting plugin://plugin.video.fen/?mode=build_movie_list&action=tmdb_movies_search_sets&query=
2024-12-01 10:48:22.544 T:120     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'query'
                                                   Traceback (most recent call last):
                                                     File "/home/user01/.var/app/tv.kodi.Kodi/data/addons/plugin.video.pov/resources/lib/pov.py", line 8, in <module>
                                                       routing(params)
                                                     File "/home/user01/.var/app/tv.kodi.Kodi/data/addons/plugin.video.pov/resources/lib/modules/router.py", line 125, in routing
                                                       imdb_build_keyword_results(params['media_type'], params['query'])
                                                                                                        ~~~~~~^^^^^^^^^
                                                   KeyError: 'query'
                                                   -->End of Python script error report<--
                                                   
2024-12-01 10:48:22.556 T:46      error <general>: GetDirectory - Error getting plugin://plugin.video.pov/?mode=imdb_build_keyword_results&media_type=movie&query=
2024-12-01 10:48:22.631 T:121     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'query'
                                                   Traceback (most recent call last):
                                                     File "/home/user01/.var/app/tv.kodi.Kodi/data/addons/plugin.video.pov/resources/lib/pov.py", line 8, in <module>
                                                       routing(params)
                                                     File "/home/user01/.var/app/tv.kodi.Kodi/data/addons/plugin.video.pov/resources/lib/modules/router.py", line 125, in routing
                                                       imdb_build_keyword_results(params['media_type'], params['query'])
                                                                                                        ~~~~~~^^^^^^^^^
                                                   KeyError: 'query'
                                                   -->End of Python script error report<--
                                                   
2024-12-01 10:48:22.657 T:46      error <general>: GetDirectory - Error getting plugin://plugin.video.pov/?mode=imdb_build_keyword_results&media_type=tvshow&query=
2024-12-01 10:48:22.799 T:46      error <general>: GetDirectory - Error getting  SEARCH HISTORY 

=========================

**Comment by ivarbrandt** [comment]
> This was of particular note in the log since this was a clean install and Fen has never been on here and search was set to POV

This is because some paths don't have any conditions around them and they pull directly from the path. It's most likely the Collections path for Fen that is causing this. I'll take a look later when I get a chance.

**Comment by ivarbrandt** [comment]
Alright so I've done all I can to fix those errors but you'll probably still see them because when the search window loads up, it tries to load the search paths for the POV search widgets you have enabled. If I suppress these errors then the search functionality breaks. It would be better for the POV dev to silence these errors similar to how Peter did in Fen/Fen Light. The keyboard and dialog box popping up is also on the POV side of things. I think if you disable the people widget, it won't pop up.

The search window functionality hasn't been updated since FENtastic lol. I have plans to either remove it from my skins, or completely rebuild it. Time will tell.

**Comment by meesterexx** [comment]
Thank you!
I has already disabled IMDB search and people search in the skin settings per these posts:
https://old.reddit.com/r/Addons4Kodi/comments/1h8oqgp/pov_search_error/
https://old.reddit.com/r/Addons4Kodi/comments/1h82ofs/pov_when_searching_a_movie_this_dialogue_box/

And that quieted the errors in on screen display. I will test your update as soon as I see it :)

BTW, I had heard rumor Peter was going to add torbox to fenlight once the service settles down some, so I may be switching back. For now I'm running/testing  both.
Thanks again!

**Comment by ivarbrandt** [comment]
> I will test your update as soon as I see it :)

Update is up. Changes are minimal. Like I said the search window needs to be overhauled or amputated lol.

Yeah I heard that too. Idk what torbox is tho so it's whatever for me.

**Comment by npmstart-pray** [comment]
> > Idk what torbox is tho so it's whatever for me.

Torbox is something for coco's dev to be concerned with for the time being.
